# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            StephDiraimondo
tagline:          'homepage'
description:      <img src="https://avatars3.githubusercontent.com/u/6768783?v=2&s=460" style="width:128px; height:128px;" />
url:              https://stephdiraimondo.github.io/
baseurl:          '/'
paginate:         5

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/StephDiRaimondo
