# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            StephDiraimondo
tagline:          'Da homepage'
description:      <img src="https://avatars3.githubusercontent.com/u/6768783?v=2&s=460" style="width:128px; height:128px;" />
url:              https://stephdiraimondo.github.io/
baseurl:          '/'
paginate:         5

author:
  name:           'Stéphane DI RAIMONDO'
  url:            https://twitter.com/StephDiraimondo

# Custom vars
version:          1.0.0
img_path:         public\images
github_logo:      https://sciactive.github.io/pnotify/includes/github-icon.png
menu_label:       public\images\menu.png

github:
  repo:           https://github.com/StephDiRaimondo
